# Generated by Django 4.0 on 2022-01-03 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='게시글 ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.CharField(max_length=10, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.FilePathField(null=True, verbose_name='이미지 경로')),
                ('thumbnail', models.FilePathField(null=True, verbose_name='썸네일 경로')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modified_datetime', models.DateTimeField(null=True, verbose_name='수정 날짜')),
                ('is_valid', models.BooleanField(default=1, verbose_name='게시글 유효성')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='구독자 ID')),
                ('email', models.EmailField(max_length=254, verbose_name='구독자 이메일')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='구독 날짜')),
                ('is_valid', models.BooleanField(default=1, verbose_name='구독자 유효성')),
            ],
        ),
    ]
