# Generated by Django 4.0 on 2022-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_trends_post_rename_post_reports_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='구독자 유효성'),
        ),
    ]
