# Generated by Django 4.0.1 on 2022-02-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_subscriber_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports_post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trends_post',
            name='image',
        ),
        migrations.AlterField(
            model_name='reports_post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/%Y/%m/%d', verbose_name='썸네일 경로'),
        ),
        migrations.AlterField(
            model_name='trends_post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/%Y/%m/%d', verbose_name='썸네일 경로'),
        ),
        migrations.CreateModel(
            name='trends_PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>', verbose_name='이미지 경로')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.trends_post')),
            ],
        ),
        migrations.CreateModel(
            name='reports_PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>', verbose_name='이미지 경로')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.reports_post')),
            ],
        ),
    ]
