# Generated by Django 4.0.1 on 2022-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_reports_post_image_remove_trends_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports_postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='trends_postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='이미지 경로'),
        ),
    ]
