# Generated by Django 4.0.1 on 2022-02-15 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_reports_postimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects_Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='게시글 ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('author', models.CharField(max_length=10, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/%Y/%m/%d', verbose_name='썸네일 경로')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modified_datetime', models.DateTimeField(null=True, verbose_name='수정 날짜')),
                ('is_valid', models.BooleanField(default=1, verbose_name='게시글 유효성')),
            ],
        ),
        migrations.CreateModel(
            name='projects_PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='이미지 경로')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.projects_post')),
            ],
        ),
    ]
